# Site settings
title: Kenny Fraser
email: me@kennyfraser.com
phone: 0131 208 0206
description: Kenny Fraser is a freelance Front End Web Developer in the Scottish Highlands.
# >  this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://kennyfraser.com" # the base hostname & protocol for your site
codepen_username: kennyfraserdotcom
ebay_username: kennyifraser
facebook_username: kennyifraser
github_username: kennyifraser
googleplus_username: +KennyFraserDotcom
gravatar_username: kennyifraser
linkedin_username: kennyfraser
pph_username: kenny
tripadvisor_username: kennyfraser
twitter_username: kennyfraser
youtube_username: kennyfraserdotcom

# Build settings
markdown: kramdown
